throwing
signal
	self error: 'Pinocchio exception thrown!'